version: '3'

services:
  keycloak:
    container_name: keycloak-container-java
    image: quay.io/keycloak/keycloak:23.0.3
    restart: always
    command:
      - start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_IMPORT: /tmp/realm.json
      API_ENDPOINT: http://mmock:8083/api
      API_MAX_CONNECTIONS: 3
      API_SOCKET_TIMEOUT: 4500
      API_CONNECT_TIMEOUT: 1000
      API_CONNECTION_REQUEST_TIMEOUT: 1000
      HTTP_STATS_INTERVAL: 5
    volumes:
      - ./realm.json:/tmp/realm.json
      - ./target/keycloak-custom-listener.jar:/opt/keycloak/providers/custom-event-listener.jar
      - ./startup-scripts/:/opt/jboss/startup-scripts/
    ports:
      - 8080:8080
  mmock:
    image: jordimartin/mmock
    restart: always
    volumes:
      - ./mmock-config/:/config/
    ports:
      - 8020:8082
      - 8030:8083
