version: '3.8'

services:
  keycloak:
    container_name: keycloak-container-with-spi
    image: zwo7ak/fresh-near-me-keycloak:latest
    restart: always
    command:
      - --verbose
      - start-dev
      - --spi-events-listener-custom-event-listener-api-endpoint=http://host.docker.internal:4040/register
      - --spi-events-listener-custom-event-listener-api-max-connections=3
      - --spi-events-listener-custom-event-listener-api-secret-key=YOURKEY
      - --spi-events-listener-custom-event-listener-api-socket-timeout=4500
      - --spi-events-listener-custom-event-listener-api-connect-timeout=1000
      - --spi-events-listener-custom-event-listener-api-connection-request-timeout=1000
      - --spi-events-listener-custom-event-listener-http-stats-interval=5
      - --import-realm

    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_IMPORT: /tmp/realm.json
      API_MAX_CONNECTIONS: 3
      API_SOCKET_TIMEOUT: 4500
      API_CONNECT_TIMEOUT: 1000
      API_CONNECTION_REQUEST_TIMEOUT: 1000
      HTTP_STATS_INTERVAL: 5
    volumes:
      - ./realm.json:/tmp/realm.json
    ports:
      - 18080:8080
