jobs:
  build:
    runs-on: ubuntu-latest
    environment: fresh-near-me-environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Dodany krok pobierania kodu źródłowego

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend custom keycloak Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./docker
          file: ./docker/Dockerfile
          push: true
          tags: zwo7ak/fresh-near-me-keycloak:latest
